### ISSUE TITLE
Another IMC'17 paper on video streaming

### ISSUE THREAD

**Issue by ShichangXu** [VideoForage/Video-Literature#1]
Hi, 

The list seems to miss a paper on measuring commercial video streaming performance published in IMC'17.

Dissecting VOD Services for Cellular: Performance, Root Causes and Best Practices
https://conferences.sigcomm.org/imc/2017/papers/imc17-final111.pdf

Could you add it as well? Thanks.

**Comment by malleshamdasari** [comment]
Thanks you @ShichangXu. Updated!

**Comment by ShichangXu** [comment]
Thank you!
