### ISSUE TITLE
5 papers for the Video Analytics section

### ISSUE THREAD

**Issue by wydwww** [VideoForage/Video-Literature#3]
Hi @mdasari823,

I find that the Video Analytics section is pretty empty. Here are several papers on video streaming for DL analytics. Hope you find them useful to your curation.

Reducto: On-Camera Filtering for Resource-Efficient Real-Time Video Analytics
SIGCOMM '20, http://web.cs.ucla.edu/~harryxu/papers/li-sigcomm20.pdf

Server-Driven Video Streaming for Deep Learning Inference
SIGCOMM '20, https://people.cs.uchicago.edu/~junchenj/docs/DDS-Sigcomm20.pdf

Enabling Edge-Cloud Video Analytics for Robotic Applications
INFOCOM '21, https://www.cse.ust.hk/~ywanggf/public/files/runespoor-infocom21.pdf

Scaling Video Analytics on Constrained Edge Nodes
SysML '19, https://hyeontaek.com/papers/ff-sysml2019.pdf

AWStream: adaptive wide-area streaming analytics
SIGCOMM '18, https://awstream.github.io/paper/awstream.pdf

**Comment by malleshamdasari** [comment]
Thanks, @wydwww for the papers. Can you please create a PR so I can merge it? if not I will add them sometime soon. Thanks.
